Use template for horizontal reviews
w3c/charter-timed-text pull request #52
Opened 2019-07-02 17:42 UTC by plehegar

This addresses the comment in
 https://github.com/w3c/strategy/issues/177#issuecomment-497142640

Give the current set of issues we have with groups not doing proper horizontal reviews, I concur with @samuelweiler that the charter template wording is the proper one to use for now, and should be the one used for the AC review of the charter.

2019-07-03 09:23 UTC, nigelmegitt reviewed
We actually rejected the template wording already I believe - @palemieux may be able to explain more the reasons why, if I am remembering the correct person. I'm not necessarily against introducing it again, but it is a) verbose, b) mixes in stuff that should be in the Process, and c) imposes a 3 month "must" requirement that is unrealistic in practice. 

On the last point, an example where it is unworkable is going from CR to CR. Apparently it imposes a _minimum_ duration between making the decision to republish and republishing of 3 months, even if the change doesn't affect the horizontal review comments.

2019-07-03 21:00 UTC, palemieux requested changes

2019-07-03 21:00 UTC, palemieux commented on index.html
> +          title="First Public Working Draft">FPWD</a> and at least 3 months before
This prose is already present at the end of Section 3.1.

2019-07-03 21:00 UTC, palemieux commented on index.html
> +          Interest Groups, and with the <a href="https://www.w3.org/2001/tag/"
As suggested by @nigelmegitt at https://github.com/w3c/strategy/issues/177#issuecomment-498174148, the comment at https://github.com/w3c/strategy/issues/177#issuecomment-497142640 can be addressed by replacing "the
        Working Group SHALL seek horizontal review with the W3C Horizontal Groups listed below" with something along the lines of "the
        Working Group SHALL seek review from W3C horizontal groups and other relevant W3C groups, including:"

2019-07-03 21:00 UTC, palemieux commented on index.html
>            <dt>
Add i18n group explicitly, even though it is already included in the list of horizontal groups, to address https://github.com/w3c/strategy/issues/177#issuecomment-499559628.

2019-07-03 21:00 UTC, palemieux commented
@plehegar Happy to update the PR, or let you do it. Whichever you prefer.

2019-07-09 12:28 UTC, swickr commented
@nigelmegitt commented
> ... an example where it is unworkable is going from CR to CR. Apparently it imposes a minimum duration between making the decision to republish and republishing of 3 months, even if the change doesn't affect the horizontal review comments.

I believe this is an overly literal reading of "... at least 3 months before CR".  The intent should be that reviewers are notified at least 3 months before _first entering_ CR. 

Substantive changes during CR could result in another review cycle and the WG is expected to have demonstrated review of any substantive changes prior to republishing a CR.  However, the reviewers also bear some responsibility to track changes during a CR period and raise issues if a change impacts their prior review.

2019-07-09 13:29 UTC, nigelmegitt commented
>I believe this is an overly literal reading of "... at least 3 months before CR". The intent should be that reviewers are notified at least 3 months before _first entering_ CR.

Ah, well I wasn't aware of the intent, just the wording! Inserting the word "first" before "Candidate Recommendation" would really help. It's still quite a big delay, but I understand the concerns of the HR groups and their need to manage their workload.

2019-07-31 12:01 UTC, plehegar commented
Tweaked following Ralph/Nigel direction.

2019-07-31 12:01 UTC, merged