fixed charter history table and added change log
w3c/charter-timed-text pull request #62
Opened 2020-03-23 05:51 UTC by himorin

PR for in-place change on change history section.

2020-03-23 17:21 UTC, nigelmegitt requested changes
Worth adding the other new Rec track deliverable to the change description. Other than that, looks good to me.

2020-03-23 17:21 UTC, nigelmegitt commented on index.html
> +              <td>TTML3
+ TTML Profile for Audio Description

2020-03-24 06:08 UTC, himorin commented on index.html
> +              <td>TTML3
fixed. thank you for caching!

2020-03-24 09:48 UTC, nigelmegitt commented on index.html
> +              <td>TTML3
Thank you!

2020-03-24 09:48 UTC, nigelmegitt approved these changes

2020-03-24 10:14 UTC, merged

2020-03-24 10:14 UTC, himorin commented
I will deploy shortly.

2020-03-24 10:19 UTC, tmichel07 commented
Please remove my name at the bottom of the page. I am not the Team contact for this group nor did I drafted this recharter.
Thanks,
Thierry

2020-03-24 10:31 UTC, himorin commented
> Please remove my name at the bottom of the page. I am not the Team contact for this group nor did I drafted this recharter.
> Thanks,
> Thierry

Thank you for pointing this and sorry that I haven't checked footer part... I'll modify before upload to WWW.

2020-03-24 10:43 UTC, nigelmegitt commented
>  I'll modify before upload to WWW.

Raised as #63